name: Android CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.caching=true
  GRADLE_BUILD_CACHE: true
  GRADLE_WORKER_MAX: 4

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        accept-android-sdk-licenses: true
        log-accepted-android-sdk-licenses: true

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Install Android SDK components
      run: |
        echo 'y' | $ANDROID_HOME/tools/bin/sdkmanager --install 'platforms;android-34'
        echo 'y' | $ANDROID_HOME/tools/bin/sdkmanager --install 'build-tools;34.0.0'
        echo 'y' | $ANDROID_HOME/tools/bin/sdkmanager --install 'ndk;25.2.9519653'
        echo 'y' | $ANDROID_HOME/tools/bin/sdkmanager --install 'cmake;3.22.1'

    - name: Build with Gradle
      run: |
        ./gradlew build --stacktrace --info

    - name: Run tests
      run: |
        ./gradlew testDebugUnitTest

    - name: Lint check
      run: |
        ./gradlew lintDebug

    - name: Upload Build Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-reports
        path: |
          app/build/reports/
          app/build/outputs/logs/
        retention-days: 7
        if-no-files-found: ignore

    - name: Upload Debug APK
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7
        if-no-files-found: warn

    - name: Build Release APK
      if: github.ref == 'refs/heads/main' || github.event_name == 'release'
      run: |
        ./gradlew assembleRelease --stacktrace --info

    - name: Upload Release APK
      if: github.ref == 'refs/heads/main' || github.event_name == 'release'
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk
        retention-days: 7
        if-no-files-found: warn

    - name: Upload Mapping File
      if: github.ref == 'refs/heads/main' || github.event_name == 'release'
      uses: actions/upload-artifact@v4
      with:
        name: mapping
        path: |
          app/build/outputs/mapping/release/mapping.txt
          app/build/outputs/native-debug-symbols/release/
        retention-days: 30
        if-no-files-found: warn
