name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ANDROID_HOME: /usr/local/lib/android/sdk
  ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
  
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Make license script executable
      run: chmod +x ./scripts/accept-android-licenses.sh

    - name: Accept Android SDK licenses
      shell: bash
      run: |
        # Run the license acceptance script
        ./scripts/accept-android-licenses.sh
        
        # Verify licenses were accepted
        echo "Verifying accepted licenses..."
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root=$ANDROID_HOME --verbose || true
    
    - name: Install Android SDK components
      shell: bash
      run: |
        # Install required SDK components
        echo "Installing Android SDK components..."
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install \
          "platform-tools" \
          "platforms;android-34" \
          "build-tools;34.0.0" \
          "extras;android;m2repository" \
          "extras;google;m2repository" \
          "extras;google;google_play_services" \
          "cmdline-tools;latest" \
          "emulator" \
          "patcher;v4" \
          --sdk_root=$ANDROID_HOME
        
        # Verify installation
        echo "Installed components:"
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list_installed --sdk_root=$ANDROID_HOME
    
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build --stacktrace
        
    - name: Upload build artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          **/build/outputs/**/*.apk
          **/build/outputs/**/*.aab
          **/build/reports/**/*
          **/build/logs/**/*
        retention-days: 7
        
    - name: Install Android SDK components
      run: |
        # Update SDK tools
        echo "Updating SDK tools..."
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update
        
        # Install required components
        echo "Installing platform tools..."
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools"
        
        echo "Installing build tools..."
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0"
        
        echo "Installing platform..."
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-34"
        
        # Install additional required components
        echo "Installing additional components..."
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          "extras;android;m2repository" \
          "extras;google;m2repository" \
          "extras;google;google_play_services" \
          "system-images;android-34;google_apis_playstore;x86_64"
        
        # List installed components
        echo "Installed components:"
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list_installed
        
        # Verify licenses are accepted
        echo "Checking licenses..."
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root=$ANDROID_HOME <<< "y\ny\ny\ny\ny\n" || true
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: |
        ./gradlew build --stacktrace --info
      
    - name: Run tests
      run: |
        ./gradlew testDebugUnitTest
      
    - name: Assemble debug APK
      run: |
        ./gradlew assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
