name: Android CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

# Add permissions for the workflow
permissions:
  contents: read
  packages: write
  actions: write
  security-events: write

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: |
        ./gradlew build --stacktrace

    - name: Run tests
      run: |
        ./gradlew test

    - name: Lint check
      run: |
        ./gradlew lintDebug

    - name: Upload APK
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 5
        if-no-files-found: warn

    - name: Upload build reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-reports
        path: |
          app/build/reports/
          app/build/outputs/logs/
        retention-days: 5
        if-no-files-found: ignore

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        build-tools-version: '34.0.0'
        ndk-version: '25.2.9519653'

    - name: Build Release APK
      if: github.ref == 'refs/heads/main' || github.event_name == 'release'
      run: |
        ./gradlew assembleRelease

    - name: Upload Release APK
      if: github.ref == 'refs/heads/main' || github.event_name == 'release'
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk
        retention-days: 5
        if-no-files-found: warn

    - name: Upload mapping file
      if: github.ref == 'refs/heads/main' || github.event_name == 'release'
      uses: actions/upload-artifact@v4
      with:
        name: mapping
        path: app/build/outputs/mapping/release/mapping.txt
        retention-days: 5
        if-no-files-found: warn
