name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ANDROID_HOME: /usr/local/lib/android/sdk
  ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
  
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        android-sdk-file: ${{ secrets.ANDROID_SDK_FILE }}
    
    - name: Accept Android SDK licenses
      shell: bash
      run: |
        mkdir -p $ANDROID_HOME/licenses/
        echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license
        echo -e "\n601085b94cd868dc0280f56bf00d3fb361a4d745" >> $ANDROID_HOME/licenses/android-sdk-license
        echo -e "\n33b6a2b64607f5b2f59edb85f6e435f77cecabb7" >> $ANDROID_HOME/licenses/android-sdk-license
        echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
        echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license
        
        # Accept additional licenses
        echo -e "\n84831b9409646a918e30573bab4c9c91346d8ecd" > $ANDROID_HOME/licenses/android-sdk-preview-license
        echo -e "\nd975f751698a77b662f9334dbeeb7fb70ea5acd1" > $ANDROID_HOME/licenses/android-sdk-license
        
        echo "Accepted licenses:"
        cat $ANDROID_HOME/licenses/*
    
    - name: Install Android SDK components
      shell: bash
      run: |
        # Update SDK tools
        echo "Updating SDK tools..."
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update
        
        # Install required components
        echo "Installing platform tools..."
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools"
        
        echo "Installing build tools..."
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0"
        
        echo "Installing platform..."
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-34"
        
        # Install NDK and CMake for native code
        echo "Installing NDK and CMake..."
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          "ndk;25.2.9519653" \
          "cmake;3.22.1"
        
        # Install additional required components
        echo "Installing additional components..."
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          "extras;android;m2repository" \
          "extras;google;m2repository" \
          "extras;google;google_play_services" \
          "cmdline-tools;latest" \
          "emulator" \
          "system-images;android-34;google_apis;x86_64"
        
        # Verify installation
        echo "Installed components:"
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list_installed
    
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true
    
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build --stacktrace --info --scan
    
    - name: Run tests
      run: |
        ./gradlew testDebugUnitTest
        ./gradlew connectedDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.notAnnotation=androidx.test.filters.FlakyTest
    
    - name: Upload build artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          **/build/outputs/**/*.apk
          **/build/outputs/**/*.aab
          **/build/reports/**/*
          **/build/logs/**/*
        retention-days: 7
    
    - name: List installed components
      if: ${{ failure() }}
      shell: bash
      run: |
        echo "Installed components:"
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list_installed
        
        echo "Environment variables:"
        env | sort
        
        echo "Gradle properties:"
        cat gradle.properties || true
      shell: bash
      run: |
        echo "Checking licenses..."
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root=$ANDROID_HOME <<< "y\ny\ny\ny\ny\n" || true
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: |
        ./gradlew build --stacktrace --info
      
    - name: Run tests
      run: |
        ./gradlew testDebugUnitTest
      
    - name: Assemble debug APK
      run: |
        ./gradlew assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
