name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ANDROID_HOME: /usr/local/lib/android/sdk
  ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
  
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Accept Android SDK Licenses
      shell: bash
      run: |
        # Create licenses directory if it doesn't exist
        mkdir -p "$ANDROID_HOME/licenses"
        
        # Accept all standard Android SDK licenses
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" >> "$ANDROID_HOME/licenses/android-sdk-license"
        echo "84831b9409646a918e30573bab4c9c91346d8abd" >> "$ANDROID_HOME/licenses/android-sdk-license"
        
        # Accept preview license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
        
        # Accept Google TV license
        echo "601085b94cc71ea42425f5c6230a62893f4eac9d" > "$ANDROID_HOME/licenses/android-googletv-license"
        
        # Accept SDK Patch Applier license
        echo "d975f751698a77b662f9334dbea2b1e4a3f6a4a8" > "$ANDROID_HOME/licenses/android-sdk-license-2746d5c9"
        
        # Accept Intel x86 Emulator Accelerator (HAXM) license
        echo "d9a2a6739ff824256d43d80971c3d1c69a3c389f" > "$ANDROID_HOME/licenses/intel-android-extra-license"
        
        # Accept MIPS system image license
        echo "e9acab5b5fbb560a72cfaecce8946896ff6aab9d" > "$ANDROID_HOME/licenses/mips-android-sysimage-license"
        
        # Accept Android SDK Platform-Tools license
        echo "33b6c2e2681ae2633006a445f6d1eab059b21380" > "$ANDROID_HOME/licenses/android-sdk-license"
        
        # Accept Android SDK Build-Tools license
        echo "601085b94cc77c0f54f8ca3922b5227e1cd45526" >> "$ANDROID_HOME/licenses/android-sdk-license"
        
        # Accept Google Play services license
        echo "33b6c2e2681ae2633006a445f6d1eab059b21380" >> "$ANDROID_HOME/licenses/android-sdk-license"
        
        # Accept Google Repository license
        echo "601085b94cc77c0f54f8ca3922b5227e1cd45526" >> "$ANDROID_HOME/licenses/android-sdk-license"
        
        # Verify licenses were created
        echo "License files created:"
        ls -la "$ANDROID_HOME/licenses/"
        
        # List licenses for debugging
        echo "License file contents:"
        cat "$ANDROID_HOME/licenses/"*
        
        # Accept licenses non-interactively with a timeout
        (while sleep 3; do echo "y"; done) | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root=$ANDROID_HOME >/dev/null 2>&1 || true
        
        # Update SDK components
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update --sdk_root=$ANDROID_HOME >/dev/null 2>&1 || true
    
    - name: Install Android SDK components
      shell: bash
      run: |
        # Install required SDK components
        echo "Installing Android SDK components..."
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install \
          "platform-tools" \
          "platforms;android-34" \
          "build-tools;34.0.0" \
          "extras;android;m2repository" \
          "extras;google;m2repository" \
          "extras;google;google_play_services" \
          --sdk_root=$ANDROID_HOME
        
        # List installed components for debugging
        echo -e "\nInstalled components:"
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list_installed --sdk_root=$ANDROID_HOME
    
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build --stacktrace
        
    - name: Upload build artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          **/build/outputs/**/*.apk
          **/build/outputs/**/*.aab
          **/build/reports/**/*
          **/build/logs/**/*
        retention-days: 7
        
    - name: Install Android SDK components
      run: |
        # Update SDK tools
        echo "Updating SDK tools..."
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update
        
        # Install required components
        echo "Installing platform tools..."
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools"
        
        echo "Installing build tools..."
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0"
        
        echo "Installing platform..."
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-34"
        
        # Install additional required components
        echo "Installing additional components..."
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          "extras;android;m2repository" \
          "extras;google;m2repository" \
          "extras;google;google_play_services" \
          "system-images;android-34;google_apis_playstore;x86_64"
        
        # List installed components
        echo "Installed components:"
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list_installed
        
        # Verify licenses are accepted
        echo "Checking licenses..."
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root=$ANDROID_HOME <<< "y\ny\ny\ny\ny\n" || true
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: |
        ./gradlew build --stacktrace --info
      
    - name: Run tests
      run: |
        ./gradlew testDebugUnitTest
      
    - name: Assemble debug APK
      run: |
        ./gradlew assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
